Change arg name for exporting config
Tracks change in new Flask API to fix bug on /generate POST:

return send_from_directory(directory=directory, path='emacs.d.zip')
TypeError: send_from_directory() missing 1 required positional argument: 'path'